### ISSUE TITLE
구조체는 자동으로 memberwise initializer 를 제공할 수 있는 이유가 같이 있으면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by x-0o0** [devxsby/TIL#1]
좋은 내용들 감사합니다. 흝어보는 중 클래스는 왜 memberwise 생성자를 자동으로 제공할 수 없는지에 대한 이유가 같이 들어가면 좋을 것 같아서 의견남깁니다. (클래스는 상속이 가능하고 구조체는 상속이 불가하다는 점이 관련이 있습니다.)

https://github.com/devxsby/TIL/blob/main/Swift/Struct,%20Class.md#12-%EA%B5%AC%EC%A1%B0%EC%B2%B4-%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4%EC%9D%98-%EC%83%9D%EC%84%B1-%EB%B0%8F-%EC%B4%88%EA%B8%B0%ED%99%94

**Comment by devxsby** [comment]
안녕하세요 재성님! @jaesung-0o0 🙌🏻
이전에 작성해놓고 업데이트를 안 한지 꽤 되었는데, 말씀하신 내용 추가해서 작성해두면 좋겠네요~~!
좋은 의견 남겨주셔서 감사합니다!! 🙇🏻‍♀️
